GAME_ACTIVE = False

PLAYER_TEAM_VICTORIES = 0
ENEMY_TEAM_VICTORIES = 0
CURRENT_ROUND = 0
CURRENT_SIDE = ''

PLAYER_STARTING_MONEY = 0
PLAYER_CURRENT_MONEY = PLAYER_STARTING_MONEY

BASE_WIN_EARNINGS = 3250
BASE_LOSS_EARNINGS = 1400
LOSS_STREAK = 0
LOSS_STREAK_BONUS = 500
BOMB_PLANT_BONUS = 800

KILL_BONUS_NORM = 300
KILL_BONUS_SNIPER = 100
KILL_BONUS_SMG = 600
KILL_BONUS_SHOTGUN = 900
BOMB_PLANTER_BONUS = 300
